# Generated by Django 5.2.17 on 2026-08-12 13:42

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_filename', models.CharField(max_length=255)),
                ('jd_filename', models.CharField(max_length=255)),
                ('evaluation', models.JSONField(default=dict)),
                ('resume_summary', models.TextField(blank=True)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_key', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='screening.analysissession')),
            ],
            options={
                'ordering': ['chunk_key'],
                'indexes': [models.Index(fields=['session', 'chunk_key'], name='screening_r_session_b679a7_idx')],
            },
        ),
    ]
