# Generated by Django 5.2.17 on 2026-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='candidate_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
