# Generated by Django 5.2.17 on 2026-09-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_analysissession_error_message_analysissession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
